import React from "react"
import { Tooltip } from "./Tooltip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Tooltip,
  "https://www.figma.com/design/BUqAux9bF0K5jeim9yrn5W/Simple-Design-System-(Community)?node-id=315%3A32700",
  {
    props: {
      hasBody: figma.boolean("Has Body"),
      body: figma.string("Body"),
      title: figma.string("Title"),
      placement: figma.enum("Placement", {
        Top: "top",
        Left: "left",
        Right: "right",
        Bottom: "bottom",
      }),
    },
    example: (props) => <Tooltip />,
  },
)
